Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [6]:
import numpy as np

In [7]:
# 1. Crear un arreglo de ceros de longitud 12
arr_ceros = np.zeros(12)
print(arr_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# 2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arr_2 = np.zeros(10)
arr_2[4] = 10
print(arr_2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [11]:
# 3. Crear un arreglo que tenga los números del 10 al 49
# np.arange([start, ]stop, [step, ])
arr_3 = np.arange(10, 50, 1)
print(arr_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
# 4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
arr_4 = np.arange(9).reshape(3, 3)
print(arr_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
# 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
# np.random.randint(low, high, size)
# np.mean(): Media o Promedio
arr_5 = np.random.randint(0, 200, 100)
media_5 = np.mean(arr_5)
varianza_5 = np.var(arr_5)
print("media: ", media_5, " - varianza: ", varianza_5)

media:  99.01  - varianza:  3764.2898999999993


In [30]:
# 6. Calcular la media de un arreglo usando np.sum
media_6 = np.sum(arr_5) / len(arr_5)
print(media_6)

99.01


In [31]:
# 7. Calcular la varianza de un arreglo usando np.sum y np.mean
varianza_7 = np.sum((arr_5 - media)**2) / len(arr_5)
print(varianza_7)

3764.3799


In [33]:
# 8. Crear un array de números aleatorios usando np.random.randn.
# np.random.rand(d0, d1, ..., dn)
arr_8 = np.random.rand(10)
print(arr_8)

[0.89933272 0.35078635 0.54115449 0.85522826 0.90163318 0.80555597
 0.17645493 0.88637314 0.68246446 0.97280952]
